name: GitHub Action 2
on: [push]
jobs:
  Deploy_on_S3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESSKEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Deploy
        run: aws s3 sync ./output s3://${{ secrets.AWS_BUCKET_NAME }}
  Deploy_on_cloudfront:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*' --exclude '.husky/*' --exclude 'package.json' --exclude 'package-lock.json' --exclude '.stylelintrc' --exclude '.prettierrc.js' --exclude '.eslintcache' --exclude '.gitignore' --exclude '.eslintrc.js' --exclude 'node_modules/*' --exclude 'README.md'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESSKEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Cloudfront CacheBurst
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DISTRIBUTION}} --paths "output/*"
        env:
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESSKEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
